export const CLIENT_ENROLLMENT_REQUEST = 'CLIENT_ENROLLMENT_REQUEST';
export const CLIENT_ENROLLMENT_SUCCESS = 'CLIENT_ENROLLMENT_SUCCESS';
export const CLIENT_ENROLLMENT_FAILURE = 'CLIENT_ENROLLMENT_FAILURE';