export const GET_CLIENT_NID_DETAILS_REQUEST = 'GET_CLIENT_NID_DETAILS_REQUEST';
export const GET_CLIENT_NID_DETAILS_SUCCESS = 'GET_CLIENT_NID_DETAILS_SUCCESS';
export const GET_CLIENT_NID_DETAILS_FAILURE = 'GET_CLIENT_NID_DETAILS_FAILURE';